ActivitiesConstants = Marty.createConstants [
  "ACTIVITY_CREATE"
  "ACTIVITY_CREATE_RESPONSE"
  "ACTIVITY_EDIT"
  "ACTIVITY_CANCEL"
  "ACTIVITY_UPDATE"
  "ACTIVITY_UPDATE_TEXT"
  "ACTIVITY_UPDATE_RESPONSE"
  "ACTIVITY_SAVE"
  "ACTIVITY_DELETE"
  "ACTIVITY_DELETE_RESPONSE"
]

module.exports = ActivitiesConstants